import RPADeveloperCertificateOfCompletion from "../../../images/certifications/20190607 - RPA Developer Certificate of completion.png";
import ArduinoFundamentals from "../../../images/certifications/20200308 - Arduino Fundamentals.png";
import CCASparkAndHadoopDeveloper from "../../../images/certifications/20201108 - CCA Spark And Hadoop Developer.png";
import OracleCertifiedProfessionalJavaSE11Developer from "../../../images/certifications/20210426 - Oracle Certified Professional Java SE 11 Developer.png";
import MET from "../../../images/certifications/20201113 - met.png";
import CertifiedEntryLevelPythonProgrammer from "../../../images/certifications/20210523 - Certified Entry-Level Python Programmer.png";
import ScrumFoundationProfessionalCetificateSFPC from "../../../images/certifications/20210612 - Scrum Foundation Professional Cetificate SFPC.png";
import AzureFundamentals from "../../../images/certifications/20210705 - Azure Fundamentals.png";
import RemoteWorkAndVirtualCollaborationProfessionalCertificate from "../../../images/certifications/20210722 - Remote Work and Virtual Collaboration Professional Certificate.png";
import CyberSecurityFoundationProcessionalCertificate from "../../../images/certifications/20210726 - Cyber Security Foundation Processional Certificate.png";
import AzureAIFundamentals from "../../../images/certifications/20210918 - Azure AI Fundamentals.png";
import AzureDataFundamentals from "../../../images/certifications/20211230 - Azure Data Fundamentals.png";
import UFTOneTesterSpecialist from "../../../images/certifications/20220107 - UFT One Tester Specialist.png";
import UFTOneV15CertifiedProfessionalExam from "../../../images/certifications/20220202 - UFT One v15 Certified Professional Exam.png";
import PowerBIDataAnalystAssociate from "../../../images/certifications/20220404 - Power BI Data Analyst Associate.png";
import PowerPlatformFundamentals from "../../../images/certifications/20220428 - Power Platform Fundamentals.png";
import CertifiedKubernetesAdministrator from "../../../images/certifications/20220601 - Certified Kubernetes Administrator.png";
import CertifiedKubernetesApplicationDeveloper from "../../../images/certifications/20220807 - Certified Kubernetes Application Developer.png";
import AzureCosmosSpeciality from "../../../images/certifications/20221028 - Azure Cosmos DB Developer Specialty.png";
import BusinessIntelligenceFoundationProfessionalCertificationBIFPC from "../../../images/certifications/20221216 - Business Intelligence Foundation Professional Certification BIFPC.png";
import TerraformAssociate from "../../../images/certifications/20221218 - Terraform associate.png";
import IBMEnterpriseDesignThinkingPractitioner from "../../../images/certifications/20230102 - IBM - Enterprise Design Thinking Practitioner.png";
import AzureDeveloperAssociate from "../../../images/certifications/20230226 - Azure Developer Associate.png";
import BusinessModelCanvasEssentialsProfessionalCertification from "../../../images/certifications/20230317 - Business Model Canvas Essentials Professional Certification - BMCEPC.png";
import AzureAdministratorAssociate from "../../../images/certifications/20230326 - Azure Administrator Associate.png";
import AzureSolutionsArchitectExpert from "../../../images/certifications/20230604 - Azure Solutions Architect Expert.png";
import DevOpsEngineerExpert from "../../../images/certifications/20230816 - DevOps Engineer Expert.png";
import AzureDataScientistAssociate from "../../../images/certifications/20231002 - Azure Data Scientist Associate.png";
import GraphDeveloperAssociate from "../../../images/certifications/20231210 - Graph Developer - Associate.svg";
import AzureDatabaseAdministratorAssociate from "../../../images/certifications/20231221 - Azure Database Administrator Associate.png";
import AzureDataEngineerAssociate from "../../../images/certifications/20240304 - Azure Data Engineer Associate.png";
import PowerAutomateRPADeveloperAssociate from "../../../images/certifications/20240327 - Power Automate RPA Developer Associate.png";
import AWSCloudPractitioner from "../../../images/certifications/20240504 - AWS Cloud Practitioner.png";
import ConsentExpertRecordIntegrationManagement from "../../../images/certifications/20240716 - Consent Expert Record Integration Management.png";
import DataDiscoveryAndGovernanceEXPERTPrivacyRightsAutomation from "../../../images/certifications/20240814 - Data Discovery and Governance EXPERT Privacy Rights Automation.png";
import PrivacyRightsAutomationExpertWebFormEnhancements from "../../../images/certifications/20240814 - Privacy Rights Automation Expert Web Form Enhancements.png";
import CookieConsentExpertIntegrations from "../../../images/certifications/20240819 - Cookie Consent Expert Integrations.png";
import DataDiscoveryGovernanceProfessionalModuleOverviews from "../../../images/certifications/20240830 - Data Discovery & Governance Professional Module Overviews.png";
import DataDiscoveryAndGovernanceProfessionalBackground from "../../../images/certifications/20240903 - Data Discovery & Governance Professional Background.png";
import DataDiscoveryAndGovernanceDataPolicies from "../../../images/certifications/20240909 - Data Discovery And Governance Data Policies.png";
import GitHubFoundations from "../../../images/certifications/20240917 - GitHub Foundations.png";
import BotBuilderRocketbotExpertLevel1 from "../../../images/certifications/20240920 - Bot Builder Rocketbot Expert Level 1.png";
import ConsentAndPreferencesManagementPro from "../../../images/certifications/20240927 - Consent And Preferences Management Pro.png";
import AzureNetworkEngineerAssociate from "../../../images/certifications/20241010 - Azure Network Engineer Associate.svg";
import type Certification from "./certification";

export const CategoryOrder: { [key: string]: number } = {
  Development: 0,
  Deployment: 1,
  Automation: 2,
  Data: 3,
  Cloud: 4,
  IoT: 5,
  AI: 6,
  "Data Privacy": 7,
  Others: 8,
};

const certifications: Certification[] = [
  {
    stared: true,
    link: "https://academy.uipath.com/certification",
    name: "RPA Developer Certificate of completion",
    brand: "UiPath",
    order: 1,
    code: "",
    category: "Automation",
    date: new Date("2019/06/07"),
    image: RPADeveloperCertificateOfCompletion,
  },
  {
    link: "https://certifications-assets-cf.arduino.cc/certificates/a8d0ed84-3a1c-4b71-9985-c44486ac0e28.pdf",
    name: "Arduino Fundamentals",
    order: 0,
    brand: "Arduino",
    code: "",
    category: "IoT",
    date: new Date("2020/03/08"),
    image: ArduinoFundamentals,
  },
  {
    stared: true,
    link: "https://www.cloudera.com/services-and-support/training/certification/cca-spark.html",
    name: "CCA Spark and Hadoop Developer",
    brand: "Cloudera",
    order: 0,
    code: "CCA-175",
    category: "Data",
    date: new Date("2020/11/08"),
    image: CCASparkAndHadoopDeveloper,
  },
  {
    link: "https://michiganassessment.org",
    name: "B1 MET",
    code: "",
    order: 0,
    brand: "MET",
    category: "Others",
    date: new Date("2020/11/23"),
    image: MET,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/449fcbf9-16c3-4949-a0cb-18d35278a845/public_url",
    name: "Oracle Certified Professional Java SE 11 Developer",
    code: "1Z0-816",
    brand: "Oracle",
    order: 0,
    category: "Development",
    date: new Date("2021/04/26"),
    image: OracleCertifiedProfessionalJavaSE11Developer,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/3e9780b1-9544-4b8c-834a-87be9e84d24f/public_url",
    name: "Certified Entry-Level Python Programmer",
    code: "PCEP",
    order: 1,
    brand: "Python Institute",
    category: "Development",
    date: new Date("2021/05/23"),
    image: CertifiedEntryLevelPythonProgrammer,
  },
  {
    link: "https://www.credly.com/badges/92c3aeff-9784-4560-9c4b-75804aa6ec78/public_url",
    name: "Scrum Foundation Professional Cetificate SFPC",
    code: "",
    order: 0,
    brand: "CertiProf",
    category: "Others",
    date: new Date("2021/06/12"),
    image: ScrumFoundationProfessionalCetificateSFPC,
  },
  {
    link: "https://www.credly.com/badges/470746ff-b66a-4cde-b568-42e344d37e94/public_url",
    name: "Azure Fundamentals",
    code: "AZ-900",
    order: 2,
    category: "Cloud",
    brand: "Microsoft",
    date: new Date("2021/07/05"),
    image: AzureFundamentals,
  },
  {
    link: "https://www.credly.com/badges/a2bb5a8d-cfe7-4cc5-bb2d-406780f99279/public_url",
    name: "Remote Work and Virtual Collaboration Professional Certificate",
    code: "",
    order: 0,
    brand: "Certiprof",
    category: "Others",
    date: new Date("2021/07/22"),
    image: RemoteWorkAndVirtualCollaborationProfessionalCertificate,
  },
  {
    link: "https://www.credly.com/badges/6a59814c-abd0-4c47-86c3-f1fefaef2abe/public_url",
    name: "Cyber Security Foundation Processional Certificate",
    code: "",
    order: 0,
    brand: "Certiprof",
    category: "Others",
    date: new Date("2021/07/26"),
    image: CyberSecurityFoundationProcessionalCertificate,
  },
  /*
  {
    link: ,
    name: "Cloud Modernization - Cloud Data Quality And Data Governance",
    code: "",
    brand: "Informatica",
    date: new Date("2021/08/28"),
    image: ,
  },
  {
    link: ,
    name: "Data Governance & Privacy Foundation Series Certification",
    code: "",
    brand: "Informatica",
    date: new Date("2021/09/01"),
    image: ,
  },
  {
    link: ,
    name: "Business 360 - Data Management for Supplie & Product",
    code: "",
    brand: "Informatica",
    date: new Date("2021/09/14"),
    image: ,
  },
  */
  {
    link: "https://www.credly.com/badges/a7525a08-aa7f-4417-8456-c5ca6d755dd3/public_url",
    name: "Azure AI Fundamentals",
    code: "AI-900",
    order: 1,
    category: "AI",
    brand: "Microsoft",
    date: new Date("2021/09/18"),
    image: AzureAIFundamentals,
  },
  /*
  {
    link: ,
    name: "ISO 9001 QUALITY MANAGEMENT SKILLFRONT",
    code: "",
    brand: "Skillfront",
    date: new Date("2021/11/13"),
    image: ,
  },
  */
  {
    link: "https://www.credly.com/badges/af2cbe11-7a70-49cd-8bf0-d76ef26bd65f/public_url",
    name: "Azure Data Fundamentals",
    code: "DP-900",
    category: "Data",
    order: 5,
    brand: "Microsoft",
    date: new Date("2021/12/30"),
    image: AzureDataFundamentals,
  },
  {
    link: "https://www.credly.com/badges/7cd68151-60e0-4fcd-b202-25fef4be00af/public_url",
    name: "UFT One Tester Specialist",
    order: 0,
    code: "",
    category: "Others",
    brand: "Microfocus",
    date: new Date("2022/01/07"),
    image: UFTOneTesterSpecialist,
  },
  {
    link: "https://www.credly.com/badges/da71971f-7cac-4955-a137-6cbbe44c9437/public_url",
    name: "UFT One v15 Certified Professional Exam",
    code: "",
    order: 0,
    brand: "Microfocus",
    category: "Others",
    date: new Date("2022/02/02"),
    image: UFTOneV15CertifiedProfessionalExam,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/fd099b10-920a-4092-8b5a-f045f1443cb5/public_url",
    name: "Power BI Data Analyst Associate",
    code: "PL-300",
    category: "Data",
    order: 2,
    brand: "Microsoft",
    date: new Date("2022/04/04"),
    image: PowerBIDataAnalystAssociate,
  },
  {
    link: "https://www.credly.com/badges/380dc1da-b794-4044-97cd-d408ee1015a6/public_url",
    name: "Power Platform Fundamentals",
    code: "PL-900",
    order: 4,
    brand: "Microsoft",
    category: "Automation",
    date: new Date("2022/04/28"),
    image: PowerPlatformFundamentals,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/dbae9536-2517-44fa-9e06-5160f6619d25/public_url",
    name: "Certified Kubernetes Administrator",
    code: "CKA",
    order: 1,
    category: "Deployment",
    brand: "Linux Foundation",
    date: new Date("2022/06/01"),
    image: CertifiedKubernetesAdministrator,
  },
  {
    link: "https://www.credly.com/badges/c019816c-4e12-49db-8d7a-82db968e9699/public_url",
    name: "Certified Kubernetes Application Developer",
    code: "CKAD",
    order: 0,
    brand: "Linux Foundation",
    category: "Deployment",
    date: new Date("2022/08/07"),
    image: CertifiedKubernetesApplicationDeveloper,
  },
  {
    link: "https://www.credly.com/badges/a8fd23c4-72d4-4fd3-85fd-f82584b764b7/public_url",
    name: "Azure Cosmos DB Developer Specialty",
    code: "DP-420",
    order: 1,
    brand: "Microsoft",
    category: "Data",
    date: new Date("2022/10/28"),
    image: AzureCosmosSpeciality,
  },
  {
    link: "https://www.credly.com/badges/6658b32c-ddf5-4c52-ac5b-03e7af939a95/public_url",
    name: "Business Intelligence Foundation Professional Certification BIFPC",
    order: 0,
    code: "",
    category: "Others",
    brand: "Certiprof",
    date: new Date("2022/12/16"),
    image: BusinessIntelligenceFoundationProfessionalCertificationBIFPC,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/6042cc38-1015-4c75-8260-a2a1d100bd00/public_url",
    name: "Terraform Associate",
    code: "HCTAO-002",
    order: 2,
    category: "Deployment",
    brand: "Hashicorp",
    date: new Date("2022/12/18"),
    image: TerraformAssociate,
  },
  {
    link: "https://www.credly.com/badges/e9815697-e3f4-4056-8ed1-98d7ca6ee1fd/public_url",
    name: "IBM - Enterprise Design Thinking Practitioner",
    order: 0,
    code: "",
    brand: "IBM",
    category: "Others",
    date: new Date("2023/01/02"),
    image: IBMEnterpriseDesignThinkingPractitioner,
  },
  {
    link: "https://www.credly.com/badges/18bf549c-39ae-43b4-830b-eb2a241f9835/public_url",
    name: "Azure Developer Associate",
    code: "AZ-204",
    brand: "Microsoft",
    order: 4,
    category: "Development",
    date: new Date("2023/02/26"),
    image: AzureDeveloperAssociate,
  },
  {
    link: "https://www.credly.com/badges/760a121b-2642-434a-87f9-341fca10192b/public_url",
    name: "Business Model Canvas Essentials Professional Certification - BMCEPC",
    order: 0,
    code: "",
    brand: "Certiprof",
    category: "Others",
    date: new Date("2023/03/17"),
    image: BusinessModelCanvasEssentialsProfessionalCertification,
  },
  {
    link: "https://www.credly.com/badges/4cb7a802-a3c8-4c76-aea0-7f67d9338092/public_url",
    name: "Azure Administrator Associate",
    code: "AZ-104",
    order: 1,
    brand: "Microsoft",
    category: "Cloud",
    date: new Date("2023/03/26"),
    image: AzureAdministratorAssociate,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/690852a9-8892-4d41-985c-fa9c42e61516/public_url",
    name: "Azure Solutions Architect Expert",
    code: "AZ-305",
    order: 0,
    brand: "Microsoft",
    category: "Cloud",
    date: new Date("2023/06/04"),
    image: AzureSolutionsArchitectExpert,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/b30ff7171db974de",
    name: "DevOps Engineer Expert",
    code: "AZ-400",
    order: 0,
    category: "Automation",
    brand: "Microsoft",
    date: new Date("2023/08/16"),
    image: DevOpsEngineerExpert,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/5b1959ecd5407c03",
    name: "Azure Data Scientist Associate",
    code: "DP-100",
    order: 0,
    brand: "Microsoft",
    category: "AI",
    date: new Date("2023/10/02"),
    image: AzureDataScientistAssociate,
  },
  {
    link: "https://www.apollographql.com/tutorials/certifications/ec329965-9334-4384-a5f7-cb348464c6f9",
    name: "Graph Developer - Associate",
    code: "",
    brand: "Apollo",
    order: 2,
    category: "Development",
    date: new Date("2023/12/10"),
    image: GraphDeveloperAssociate,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/46F92540CBDEC94B",
    name: "Azure Database Administrator Associate",
    code: "DP-300",
    order: 3,
    category: "Data",
    brand: "Microsoft",
    date: new Date("2023/12/21"),
    image: AzureDatabaseAdministratorAssociate,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/1A7FBCA0D918570C",
    name: "Azure Data Engineer Associate",
    code: "DP-203",
    order: 4,
    category: "Data",
    brand: "Microsoft",
    date: new Date("2024/03/04"),
    image: AzureDataEngineerAssociate,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/95faf1625d78d34a",
    name: "Power Automate RPA Developer Associate",
    code: "PL-500",
    order: 3,
    category: "Automation",
    brand: "Microsoft",
    date: new Date("2024/03/27"),
    image: PowerAutomateRPADeveloperAssociate,
  },
  {
    stared: true,
    link: "https://www.credly.com/badges/39d828a4-c03a-4c2c-9589-623dd662a115/public_url",
    name: "AWS Cloud Practitioner",
    order: 3,
    code: "CLF-C02",
    category: "Cloud",
    brand: "AWS",
    date: new Date("2024/05/04"),
    image: AWSCloudPractitioner,
  },
  {
    link: "https://www.onetrust.com/certifications/consent-record-integration-and-management-certification",
    name: "Consent Expert: Record Integration & Management",
    code: "",
    order: 0,
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/07/16"),
    image: ConsentExpertRecordIntegrationManagement,
  },
  {
    link: "https://www.onetrust.com/certifications/data-subject-requests-expert-certification/",
    name: "Privacy Rights Automation Expert: Web form enhancements",
    order: 4,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/08/14"),
    image: PrivacyRightsAutomationExpertWebFormEnhancements,
  },
  {
    link: "https://www.onetrust.com/certifications/data-discovery-privacy-rights-automation-certification/",
    name: "Data Discovery and Governance EXPERT Privacy Rights Automation",
    order: 2,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/08/14"),
    image: DataDiscoveryAndGovernanceEXPERTPrivacyRightsAutomation,
  },
  {
    link: "https://www.onetrust.com/certifications/website-scanning-cookies-consent-expert-certification/",
    name: "Cookie Consent Expert: Integrations",
    order: 1,
    code: "",
    brand: "One Trust",
    category: "Data Privacy",
    date: new Date("2024/08/19"),
    image: CookieConsentExpertIntegrations,
  },
  {
    link: "https://www.onetrust.com/certifications/data-discovery-and-governance-professional-certification/",
    name: "Data Discovery & Governance Professional Module Overviews",
    order: 3,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/08/30"),
    image: DataDiscoveryGovernanceProfessionalModuleOverviews,
  },
  {
    link: "https://www.onetrust.com/certifications/data-discovery-and-governance-professional-certification/",
    name: "Data Discovery & Governance Professional Background",
    order: 4,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/09/03"),
    image: DataDiscoveryAndGovernanceProfessionalBackground,
  },

  {
    link: "https://www.onetrust.com/certifications/data-discovery-data-policies-certification/",
    name: "Data Discovery and Governance Data Policies",
    order: 4,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/09/09"),
    image: DataDiscoveryAndGovernanceDataPolicies,
  },
  {
    link: "https://www.credly.com/badges/3d39e55e-5b24-4947-9eed-a14e0b5d493a/linked_in_profile",
    name: "GitHub Foundation",
    order: 3,
    code: "",
    category: "Development",
    brand: "Github",
    date: new Date("2024/09/17"),
    image: GitHubFoundations,
  },
  {
    link: "https://certificate.rocketbot.co/badges/b835748e-d34e-924e-a4d8-9e8ffa7b42b1",
    name: "Consent & Preferences Management Pro",
    order: 4,
    code: "",
    category: "Data Privacy",
    brand: "One Trust",
    date: new Date("2024/09/27"),
    image: ConsentAndPreferencesManagementPro,
  },
  {
    link: "https://www.onetrust.com/certifications/consent-preference-management-professional-certification/",
    name: "Bot Builder Rocketbot Expert Level 1",
    order: 2,
    code: "",
    category: "Automation",
    brand: "RocketBot",
    date: new Date("2024/09/20"),
    image: BotBuilderRocketbotExpertLevel1,
  },
  {
    link: "https://learn.microsoft.com/en-us/users/danny270793/credentials/c33ec4db199f5ec2",
    name: "Azure Network Engineer Associate",
    order: 4,
    code: "AZ-700",
    category: "Cloud",
    brand: "Microsoft",
    date: new Date("2024/10/10"),
    image: AzureNetworkEngineerAssociate,
  },
];
export default certifications;
